repos:
- repo: https://github.com/tox-dev/pyproject-fmt
  rev: 0.12.0
  hooks:
    - id: pyproject-fmt

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.272
  hooks:
    - id: ruff